### ISSUE TITLE
gitbook  翻译进度

### ISSUE THREAD

**Issue by andurils** [panxl6/Kotlin-in-action#2]
GITBOOK上的内容看完了，谢谢您的分享。请问下是否为商业翻译，后续章节是否会继续放出？ 
如果不放出，我就看英文版去了..

**Comment by panxl6** [comment]
翻译项目只是为了丰富kotlin的学习资料。没有别的目的。翻译进度跟不上确实是个大问题。您还是先看着英文版吧！

**Comment by andurils** [comment]
哦  谢谢分享 ：）
